spring.application.name=ecommerce

spring.datasource.url=jdbc:h2:mem:ecommerce
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=vishal
spring.datasource.password=


spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true


spring.h2.console.enabled=true


jwt.secret=Fda7eqg8hVpH0USdeoA0uAZJpRLA6N1ry77l2ckIkQL

stripe.secret.key=${STRIPE_SECRET_KEY}


jwt.expiration=86400000